alias ll='exa -al --group --color=always --group-directories-first'
alias la='exa -a --group --color=always --group-directories-first'
alias l='exa -l --group --color=always --group-directories-first'
#alias ll='ls -Alh --dereference-command-line-symlink-to-dir'
#alias la='ls -A --dereference-command-line-symlink-to-dir'
#alias l='ls -lh --dereference-command-line-symlink-to-dir'
alias h='history'
alias i='inxi --full --ip --uuid --label --usb --raid --partitions-full --memory'
alias e='micro'
alias b='br --show-git-info --only-folders --show-root-fs --no-trim-root'
alias c='batcat'
alias scanip="nmap -sn 192.168.1.0/24 | awk '/for/ {print substr(\$0,22)}'"
alias gitlog='git log --pretty=format:"%h %s" --graph'
alias lg='lazygit'
alias easy="cd $HOME/easy-diffusion && ./start.sh"
